### ISSUE TITLE
[btcatomicswap] sendrawtransaction wrong param

### ISSUE THREAD

**Issue by vctt94** [decred/atomicswap#110]
after commit https://github.com/bitcoin/bitcoin/commit/c033c4b5cef89a654e4d9d5c5f9bd823871b068b bitcoin switched sendrawtransaction to use maxFeeRate instead of allowHighFees. 

This will trhow an error on btcatomicswap: `Second argument must be numeric (maxfeerate) and no longer supports a boolean. To allow a transaction with high fees, set maxfeerate to 0.`

**Comment by jrick** [comment]
Was fixed by #111
