### ISSUE TITLE
AS between BTC and LTC

### ISSUE THREAD

**Issue by art32** [decred/atomicswap#21]
Hi, with the help of your utility it is possible to make a atomic swap between BTC and LTC?

**Comment by davecgh** [comment]
Yes.  It has already been done as well.  You'd want to use `ltcatomicswap` and `btcatomicswap`.  When following the instructions just replace the `dcratomicswap` accordingly.

**Comment by art32** [comment]
@davecgh, thank you, for me it was not obvious from the documentation :)
