### ISSUE TITLE
Refund Transaction Not Being Confirmed

### ISSUE THREAD

**Issue by HamishMacEwan** [decred/atomicswap#22]
Hi,

Thanks very much for the amazing work you are doing here to make swaps available.  The consequences can only be imagined.

For once in my life I decided to be cautious and exercise the failure option first.  To that end I created and initiated a contract (using ltcatomicswap) then waited the 48 hours for the refund to be available.

I submitted the refund transaction via https://live.blockcypher.com/ltc/pushtx/ but it still hasn't confirmed, and as far as I can tell it hasn't been relayed, other Litecoin block explorers can't find the transaction.

Publishing the refund transaction using litecoin 0.14.2 sendrawtransaction "failed: 64: version (code -26)"

( `getinfo`  returns in part: "version": 140200,
"protocolversion": 70015,
"walletversion": 60000)

The current situation is: https://live.blockcypher.com/ltc/address/3CH9sjVpApvQR31U8niMyrYg3MzR9466uS/ 

Suggestions to remedy the situation or help me understand what I've done wrong would be appreciated.

In case it's significant, the refund address used in the `initiate` below is from the wallet that the local litecoin instance controls.  
```
ltcatomicswap -rpcuser user -rpcpass atomic initiate LiYeAuZHCYUDxe6zpRSthneYew98My7meB 0.5
warning: falling back to mempool relay fee policy
Secret:      [REDACTED]
Secret hash: 80add26acbcd57e618a77573e5fe1696e85d9793

Contract fee: 0.000224 LTC (0.00100000 LTC/kB)
Refund fee:   0.000281 LTC (0.00102182 LTC/kB)

Contract (ZNdPisrRRMg7kYTxyFhGMFxgFCKAT4VUKU):
63a61480add26acbcd57e618a77573e5fe1696e85d97938876a914ffd3b1bd0c5a94762f41b155697e2d267a28c57e67046b17cb59b17576a9145a238ba258c2ec0bc3076038d8f3f97cd65b095a6888ac

Contract transaction (9948ad4738aba10ba57171ff2703fd41bbb6e09fd058fdac95c9fa4d0c27e108):
0200000001bf922f652c3ab84d233840a010e5e38ddc175de9cd0aaf015d1271d759ac1d95000000006b4830450221008208604bd6119c65a2fa7ea4a268f0831129fda31f0dd22f90b5138fc4d55d8102206933d1ab5d8476f401e26be7aca63a34d6e63fb1eaf893cc6238170640fc8f02012103bc62efac4d28be76d073e21bd924ce2a294a7dada17cfab7c186925e3f576b8ffeffffff0282d8464f020000001976a914da4cd7aac092d0acb20488f816214778171e39e488ac80f0fa020000000017a914742609c49d65ae0ed34416284f56773ecef240078700000000

Refund transaction (35452de16c7856c97214bbfc5f64978dcd263180db35ceb9c85f5ef32b88a181):
000000000108e1270c4dfac995acfd58d09fe0b6bb41fd0327ff7171a50ba1ab3847ad489901000000be47304402205838b0907d8819277909355cfbe72642cc3501fc976b4f8d1aa71292071fabde0220105692802184ec8176052654b74dd4db438637c9609398e02931a884314808a901210371b18eeab61b58d22e3c92ef0826e619dfa110a588d7db312421085e71a7b97d004c5163a61480add26acbcd57e618a77573e5fe1696e85d97938876a914ffd3b1bd0c5a94762f41b155697e2d267a28c57e67046b17cb59b17576a9145a238ba258c2ec0bc3076038d8f3f97cd65b095a6888ac0000000001bc82fa02000000001976a914da4cd7aac092d0acb20488f816214778171e39e488ac6b17cb59

Publish contract transaction? [y/N] y
Published contract transaction (9948ad4738aba10ba57171ff2703fd41bbb6e09fd058fdac95c9fa4d0c27e108)
```

**Comment by jrick** [comment]
Thanks for testing and reporting.  Looks like an error with the refund transaction being created with the wrong tx version.  I'll get that fixed, and i think it would also be a good idea to add a separate refund step to the commands so that refunds can be created after the fact if necessary (if the refund tx was lost, if it was performed on a blockchain that still had malleable txs, etc.)

**Comment by HamishMacEwan** [comment]
Thank you.

While I'm relieved to know the problem isn't of my creation, it would help to know if I can correct the issue (and recover my LTC) by adjusting the transaction?  Naively comparing the contract and refund transactions, it would seem `02` replacing the leading `00` might suffice?

Or could I continue and `redeem` using my knowledge of the `secret`?

**Comment by jrick** [comment]
You'll need to use redeem once it's ready.  Manually modifying the tx like that will cause the signatures validation to fail.  I just implemented the redeem command for the dcr tool, in process of testing it now, and then will port it to the rest.

**Comment by jrick** [comment]
If you used your own address as the redeemer's address in the contract, you could also spend it with the redeem command and the secret.  I'm still adding that refund command but that will allow you sooner access to those funds.

**Comment by jrick** [comment]
@HamishMacEwan give #24 a try if you haven't already redeemed the output.

**Comment by HamishMacEwan** [comment]
I have attempted to `redeem` the contract (the advantage of being party A & B) but as far as I can tell without success.

Although `auditcontract` works:
```

ltcatomicswap auditcontract 63a61480add26acbcd57e618a77573e5fe1696e85d97938876a914ffd3b1bd0c5a94762f41b155697e2d267a28c57e67046b17cb59b17576a9145a238ba258c2ec0bc3076038d8f3f97cd65b095a6888ac 0200000001bf922f652c3ab84d233840a010e5e38ddc175de9cd0aaf015d1271d759ac1d95000000006b4830450221008208604bd6119c65a2fa7ea4a268f0831129fda31f0dd22f90b5138fc4d55d8102206933d1ab5d8476f401e26be7aca63a34d6e63fb1eaf893cc6238170640fc8f02012103bc62efac4d28be76d073e21bd924ce2a294a7dada17cfab7c186925e3f576b8ffeffffff0282d8464f020000001976a914da4cd7aac092d0acb20488f816214778171e39e488ac80f0fa020000000017a914742609c49d65ae0ed34416284f56773ecef240078700000000
Contract address:        ZNdPisrRRMg7kYTxyFhGMFxgFCKAT4VUKU
Contract value:          0.5 LTC
Recipient address:       LiYeAuZHCYUDxe6zpRSthneYew98My7meB
Author's refund address: LTSZfDdjmtURi35Auc7eHBpHH4aCdADPr8

Secret hash: 80add26acbcd57e618a77573e5fe1696e85d9793

Locktime: 2017-09-27 03:13:47 +0000 UTC
Contract refund time lock has expired
```
`redeem` (same paramters plus `secret`):
```

ltcatomicswap redeem 63a61480add26acbcd57e618a77573e5fe1696e85d97938876a914ffd3b1bd0c5a94762f41b155697e2d267a28c57e67046b17cb59b17576a9145a238ba258c2ec0bc3076038d8f3f97cd65b095a6888ac 0200000001bf922f652c3ab84d233840a010e5e38ddc175de9cd0aaf015d1271d759ac1d95000000006b4830450221008208604bd6119c65a2fa7ea4a268f0831129fda31f0dd22f90b5138fc4d55d8102206933d1ab5d8476f401e26be7aca63a34d6e63fb1eaf893cc6238170640fc8f02012103bc62efac4d28be76d073e21bd924ce2a294a7dada17cfab7c186925e3f576b8ffeffffff0282d8464f020000001976a914da4cd7aac092d0acb20488f816214778171e39e488ac80f0fa020000000017a914742609c49d65ae0ed34416284f56773ecef240078700000000 [REDACTED `secret`]
```
Complains:
`
getrawchangeaddres: status code: 401, response: ""
`

Thanks for your suggestion, but #24 is a bit beyond my git-ability.  I can just manage to `git pull origin master` but no more.

**Comment by jrick** [comment]
That 401 error indicates an authentication error (your rpc user and password weren't set or didn't match).

To try out that PR:

```
git fetch https://github.com/jrick/atomicswap refundcmd:refundcmd
git checkout refundcmd
```

Use `git checkout master` to go back to master when you're done.

**Comment by HamishMacEwan** [comment]
*DOH*

Given that oversight, I think I'd be pushing my luck with anything that advanced.  You wouldn't believe how many times I used walletpassphrase to fix that 401...

**Comment by HamishMacEwan** [comment]
Blockcypher is having a cow:   DOUBLE SPEND ATTEMPT!  

https://live.blockcypher.com/ltc/address/3CH9sjVpApvQR31U8niMyrYg3MzR9466uS/

But things are looking good.  

This won't be my last experiment with this technique, so I'll get chance to try #24  Thanks @jrick!

**Comment by HamishMacEwan** [comment]
Ok, so I got brave and after completely losing my way somehow ended up with a working 6 option ltcatomicswap and a new and improved refund transaction.

```
020000000108e1270c4dfac995acfd58d09fe0b6bb41fd0327ff7171a50ba1ab3847ad489901000000be473044022037e68d167b538636e8d9e7cbf8293e0947533f6eac7c81194be1993475edeb88022068e928955e8e9c6bcf383164f68373d2c885f9bfdba46bba9785db25d42a1c5601210371b18eeab61b58d22e3c92ef0826e619dfa110a588d7db312421085e71a7b97d004c5163a61480add26acbcd57e618a77573e5fe1696e85d97938876a914ffd3b1bd0c5a94762f41b155697e2d267a28c57e67046b17cb59b17576a9145a238ba258c2ec0bc3076038d8f3f97cd65b095a6888ac0000000001bc82fa02000000001976a91468a1a081207bb54a63bb8accb0bcfe8bc9a188e088ac6b17cb59
```

sendrawtransaction quite properly complained `18: bad-txns-inputs-spent (code -26)` but clearly the tx version was right this time.

**Comment by jrick** [comment]
That transaction is invalid because it is a double spend of the redeem transaction you already created.
