### ISSUE TITLE
btcatomicswap: error from RPC server

### ISSUE THREAD

**Issue by art32** [decred/atomicswap#26]
Hi!
I tried to run AS between DCR and BTC, but btcatomicswap returns this error:

`warning: falling back to mempool relay fee policy`
`fundrawtransaction: -3: Expected type bool, got object`

with any commands `initiate` or `participate`.

Bitcoin node version:
    "bitcore-lib": "^v0.13.19",
    "bitcore-node": "^3.1.3",
    "bitcore-wallet-service": "^2.1.0",
    "insight-api": "^0.4.3"

**Comment by jrick** [comment]
This is talking to a Bitcoin Core RPC server?

**Comment by art32** [comment]
@jrick yes, bitcore v4.1.1

**Comment by jrick** [comment]
Bitcore (a BitPay projecxt) is a very different thing than Bitcoin Core despite the similar names.

**Comment by art32** [comment]
I did not know, I'm used Bitcore. It's problem?

**Comment by jrick** [comment]
Bitcoin Core's wallet is the only bitcoin wallet we support at this time.

**Comment by jrick** [comment]
Closing since this occurred trying to use RPC with an unsupported wallet.
