### ISSUE TITLE
Bitcoin Core forks: use estimatesmartfee

### ISSUE THREAD

**Issue by jrick** [decred/atomicswap#32]
Since Bitcoin Core 0.14.2, estimatefee has been deprecated and clients are encouraged to use estimatesmartfee instead.  Any atomicswap tools working with wallets that are synced with this Bitcoin Core change should be using estimatesmartfee instead of estimatefee.

**Comment by xaur** [comment]
What is the general strategy of supporting various Bitcoin Core versions that atomicswap depends on? Support only latest BC version, support several past BC versions in latest atomicswap version, or maintain several branches of atomicswap, each for certain BC version?

**Comment by jrick** [comment]
practically I think it makes the most sense to target the latest release, especially as soft forks are rolled out that can make older wallet software irrelevant.

**Comment by jrick** [comment]
#61 updates btcatomicswap to use estimatesmartfee, and is a model for other coins that are forked from Bitcoin Core.

**Comment by jrick** [comment]
Fixed by #65.
