### ISSUE TITLE
"getinfo" no longer Available on bitcoin-core 0.16.0. "redeem" operation fails calculating fees

### ISSUE THREAD

**Issue by girino** [decred/atomicswap#60]
Due to the removal of the depracated RPC call "getinfo", btcatomicswap fails when calling the "redeem" command.

Use of getinfo:
https://github.com/decred/atomicswap/blob/master/cmd/btcatomicswap/main.go#L460

From the BitcoinCore release notes:
> The deprecated RPC getinfo was removed. It is recommended that the more specific RPCs are used:
> getblockchaininfo
> getnetworkinfo
> getwalletinfo
> getmininginfo

**Comment by jrick** [comment]
Thanks for the report, I'll look into this.
