### ISSUE TITLE
tls: transport connection broken

### ISSUE THREAD

**Issue by cronos-polis** [decred/atomicswap#62]
Hello,
I am trying to implement atomicswaps to Polis a cryptocurrency with a X11 Algorith. The go version of the full node is ready, also the wallet rpc and the command line.

I am testing with btcatomicswap but when I try to participate on the initiated contract I get a response:

`getrawchangeaddress: Post http://localhost:24128: net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02\x16"`

On the btcwallet side I get other error: 

`http: TLS handshake error from [::1]:53060: tls: oversized record received with length 21536`

Any help from were to start solving this issue?

Thanks!

**Comment by jrick** [comment]
btcatomicswap works with bitcoind/bitcoin-qt, not btcwallet.

**Comment by cronos-polis** [comment]
Thanks! Will test right now.

**Comment by cronos-polis** [comment]
Thanks, I was stuck with this. Now develop is working.
