### ISSUE TITLE
support requirements

### ISSUE THREAD

**Issue by tofutim** [decred/atomicswap#82]
Hi, I am interested in adding atomicswap capability to a Bitcoin-based altcoin. Is there a checklist of required capabilities?

**Update.** I found https://blog.decred.org/2017/09/20/On-Chain-Atomic-Swaps/

> In order to perform an on-chain atomic swap between 2 cryptocurrencies, there are several prerequisites. Both chains must support:
> 
> - branched transaction scripts
> - the same hash algorithm in both chains’ transaction scripts
> - signature checks in transaction scripts
> - CheckLockTimeVerify or CheckSequenceVerify (“CLTV” and “CSV” for short) in transaction scripts
> 
> Since Decred and Litecoin are forks of Bitcoin, the first 3 conditions are trivially satisfied. Further, both Decred and Litecoin have been tracking updates from Bitcoin, so they both support CLTV. The CLTV/CSV support is used to effect a refund, in the cases where either party does not complete part of the process. With some further work on part of other Bitcoin-based cryptocurrency projects, this on-chain atomic swap can occur between any pair of cryptocurrencies that satisfy the above constraints.

Some of these items, I can add in, but is it truly necessary for the same hash algorithm in both chains? Why is this needed?

**Comment by jrick** [comment]
Yes, both chains must support the same hash opcode. We use SHA256.

**Comment by jrick** [comment]
Closing due to age and the question has been answered.
