### ISSUE TITLE
I'd like to use this as a library

### ISSUE THREAD

**Issue by tanevanwifferen** [decred/atomicswap#87]
Hey there,

I would like to use this code in my own proejct, with a few changes that allows to use this code as a go plugin. I propose the following changes:

```
func getSettingsKeys() []string {}
func setSettings(settings map[string]string) err {}
```

settings would entail rpc connection details, or anything required for the plugin to run correctly. 

Is this interesting for you too, or shall I fork the repo for myself?

**Comment by jrick** [comment]
I think you should fork it, since I don't really understand the proposed changes.

The Go plugin idea sounds useful.  I'd like to see how that turns out.
