### ISSUE TITLE
New coin want to be swaped

### ISSUE THREAD

**Issue by luoshang722** [decred/atomicswap#91]
Now i want to add support of Qtum for atomicswap, but Qtum does not have a Go implement. Should i write an alternative full node by GO for qtum first? If it is, which xxxd should i fork if want it easier. btcd or ltc or which one ?

**Comment by jrick** [comment]
You don't need a full node.  These tools only communicate with a wallet over RPC.  The references to code from full nodes is due to using those packages as libraries (for decoding transactions, building scripts, etc.).

**Comment by jrick** [comment]
Qtum support is merged.
